### ISSUE TITLE
`treehouses sshtunnel` refactor

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#1198]
right now we defined the standard port to tunnel
in our next iteration we want to open the possibility
to define other ports
and also accommodate multiple tunnels

watch out that for multiple sshtunnels we also want to refactor
`treehouses default network`

**Comment by kjong** [comment]
## Adding new tunnels
In current implementation, adding a new port will "overwrite" the current tunnel settings

Two potential solutions for adding new tunnels:
#### Select method
- When adding a new port, save it to it's own file (`/etc/tunnel-$port`)
- Implement a "select" method (`cp /etc/tunnel-$port /etc/tunnel`)
- Multiple hosts? Then `/etc/tunnel-$host-$port`

#### Append method
- Instead of saving each new port to it's own file and selecting which file to cp to `/etc/tunnel`, append to `/etc/tunnel`
- Example `/etc/tunnel`:
```
#!/bin/bash

/usr/bin/autossh -f -T -N -q -4 -M $port1 <-- keep using $port1 for base monitoring port
                                -R 64422:127.0.1.1:22
                                -R 64622:127.0.1.1:22  <-- append new port
                                  ...
                                $host
```

Current:
```
root@kjong:~/cli# ./cli.sh sshtunnel list
Ports:
 local   -> external
    22   -> 64422
    80   -> 64480
    2200 -> 64482
    4949 -> 64449
    5984 -> 64484
Host: ole@pirate.ole.org
```

Proposed:
```
root@kjong:~/cli# ./cli.sh sshtunnel list
Ports:
 local   -> external
    22   -> 64422, 64622
    80   -> 64480, 64680
    2200 -> 64482, 64682
    4949 -> 64449, 64649
    5984 -> 64484, 64684
Host: ole@pirate.ole.org
```

Refactor commands:
`treehouses sshtunnel add 65400 user@server.org` -->
`treehouses sshtunnel add tunnels 65400 user@server.org`

`treehouses sshtunnel remove 65400 user@server.org` -->
`treehouses sshtunnel remove tunnels 65400 user@server.org`

## Adding new ports
In current implementation, ports are defined as such:
```
portssh=$((portinterval + 22))
portweb=$((portinterval + 80))
portcouchdb=$((portinterval + 84))
portnewcouchdb=$((portinterval + 82))
portmunin=$((portinterval + 49))
```

In order to add/remove new ports, the ports have to be saved to an external file so they can be saved between sessions (probably don't want to make script self-modifying)

External file --> `/etc/ports-list`?

Ports added to/removed from this file

`treehouses sshtunnel add port $portname xx` adds:
```
$portname=$((portinterval + xx))
```

`treehouses sshtunnel remove port $portname` to remove ports
